clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "



while :
do

  python3 /home/ubuntu/Desktop/dieustp/BTC1.py &
  python3 /home/ubuntu/Desktop/dieustp/ETH1.py &
  python3 /home/ubuntu/Desktop/dieustp/USDT1.py &
  python3 /home/ubuntu/Desktop/dieustp/BNB1.py &
  python3 /home/ubuntu/Desktop/dieustp/XRP1.py &
  python3 /home/ubuntu/Desktop/dieustp/BUSD1.py &
  python3 /home/ubuntu/Desktop/dieustp/ADA1.py &
  python3 /home/ubuntu/Desktop/dieustp/DOGE1.py &
  python3 /home/ubuntu/Desktop/dieustp/MATIC1.py &
  python3 /home/ubuntu/Desktop/dieustp/SOL1.py &
  python3 /home/ubuntu/Desktop/dieustp/DOT1.py &
  python3 /home/ubuntu/Desktop/dieustp/SHIB1.py &
  python3 /home/ubuntu/Desktop/dieustp/LTC1.py &
  python3 /home/ubuntu/Desktop/dieustp/TRX1.py &
  python3 /home/ubuntu/Desktop/dieustp/AVAX1.py &
  python3 /home/ubuntu/Desktop/dieustp/UNI1.py &
  python3 /home/ubuntu/Desktop/dieustp/WBTC1.py &
  python3 /home/ubuntu/Desktop/dieustp/ATOM1.py &
  python3 /home/ubuntu/Desktop/dieustp/LINK1.py &
  python3 /home/ubuntu/Desktop/dieustp/ETC1.py &
  python3 /home/ubuntu/Desktop/dieustp/XMR1.py &
  python3 /home/ubuntu/Desktop/dieustp/BCH1.py &
  python3 /home/ubuntu/Desktop/dieustp/APT1.py &
  python3 /home/ubuntu/Desktop/dieustp/LDO1.py &
  python3 /home/ubuntu/Desktop/dieustp/XLM1.py &
  python3 /home/ubuntu/Desktop/dieustp/HBAR1.py &
  python3 /home/ubuntu/Desktop/dieustp/FIL1.py &
  python3 /home/ubuntu/Desktop/dieustp/NEAR1.py &
  python3 /home/ubuntu/Desktop/dieustp/APE1.py &
  python3 /home/ubuntu/Desktop/dieustp/ALGO1.py &
  python3 /home/ubuntu/Desktop/dieustp/VET1.py &
  python3 /home/ubuntu/Desktop/dieustp/QNT1.py &
  python3 /home/ubuntu/Desktop/dieustp/ICP1.py &
  python3 /home/ubuntu/Desktop/dieustp/GRT1.py &
  python3 /home/ubuntu/Desktop/dieustp/FTM1.py &
  python3 /home/ubuntu/Desktop/dieustp/MANA1.py &
  python3 /home/ubuntu/Desktop/dieustp/AAVE1.py &
  python3 /home/ubuntu/Desktop/dieustp/EOS1.py &
  python3 /home/ubuntu/Desktop/dieustp/EGLD1.py &
  python3 /home/ubuntu/Desktop/dieustp/AXS1.py &
  python3 /home/ubuntu/Desktop/dieustp/FLOW1.py &
  python3 /home/ubuntu/Desktop/dieustp/THETA1.py &
  python3 /home/ubuntu/Desktop/dieustp/SAND1.py &
  python3 /home/ubuntu/Desktop/dieustp/XTZ1.py &
  python3 /home/ubuntu/Desktop/dieustp/LUNC1.py &
  python3 /home/ubuntu/Desktop/dieustp/IMX1.py &
  python3 /home/ubuntu/Desktop/dieustp/MINA1.py &
  python3 /home/ubuntu/Desktop/dieustp/CHZ1.py &
  python3 /home/ubuntu/Desktop/dieustp/RPL1.py &
  python3 /home/ubuntu/Desktop/dieustp/CRV1.py &
  python3 /home/ubuntu/Desktop/dieustp/FXS1.py &
  python3 /home/ubuntu/Desktop/dieustp/DASH1.py &
  python3 /home/ubuntu/Desktop/dieustp/ZEC1.py &
  python3 /home/ubuntu/Desktop/dieustp/MKR1.py &
  python3 /home/ubuntu/Desktop/dieustp/BTTC1.py &
  python3 /home/ubuntu/Desktop/dieustp/CAKE1.py &
  python3 /home/ubuntu/Desktop/dieustp/KLAY1.py &
  python3 /home/ubuntu/Desktop/dieustp/XEC1.py &
  python3 /home/ubuntu/Desktop/dieustp/GMX1.py &
  python3 /home/ubuntu/Desktop/dieustp/IOTA1.py &
  python3 /home/ubuntu/Desktop/dieustp/SNX1.py &
  python3 /home/ubuntu/Desktop/dieustp/NEO1.py &
  python3 /home/ubuntu/Desktop/dieustp/TWT1.py &
  python3 /home/ubuntu/Desktop/dieustp/OP1.py &
  python3 /home/ubuntu/Desktop/dieustp/RUNE1.py &
  python3 /home/ubuntu/Desktop/dieustp/LRC1.py &
  python3 /home/ubuntu/Desktop/dieustp/FTT1.py &
  python3 /home/ubuntu/Desktop/dieustp/AGIX1.py &
  python3 /home/ubuntu/Desktop/dieustp/PAXG1.py &
  python3 /home/ubuntu/Desktop/dieustp/OSMO1.py &
  python3 /home/ubuntu/Desktop/dieustp/ZIL1.py &
  python3 /home/ubuntu/Desktop/dieustp/BNX1.py &
  python3 /home/ubuntu/Desktop/dieustp/CVX1.py &
  python3 /home/ubuntu/Desktop/dieustp/ROSE1.py &
  python3 /home/ubuntu/Desktop/dieustp/ROSE1.py &
  python3 /home/ubuntu/Desktop/dieustp/RNDR1.py &
  python3 /home/ubuntu/Desktop/dieustp/ENJ1.py &
  python3 /home/ubuntu/Desktop/dieustp/BAT1.py &
  python3 /home/ubuntu/Desktop/dieustp/STX1.py &
  python3 /home/ubuntu/Desktop/dieustp/DYDX1.py &
  python3 /home/ubuntu/Desktop/dieustp/1INCH1.py &
  python3 /home/ubuntu/Desktop/dieustp/LUNA1.py &
  python3 /home/ubuntu/Desktop/dieustp/NEXO1.py &
  python3 /home/ubuntu/Desktop/dieustp/ASTR1.py &
  python3 /home/ubuntu/Desktop/dieustp/AR1.py &
  python3 /home/ubuntu/Desktop/dieustp/CELO1.py &
  python3 /home/ubuntu/Desktop/dieustp/HOT1.py &
  python3 /home/ubuntu/Desktop/dieustp/KAVA1.py &
  python3 /home/ubuntu/Desktop/dieustp/MAGIC1.py &
  python3 /home/ubuntu/Desktop/dieustp/COMP1.py &
  python3 /home/ubuntu/Desktop/dieustp/RVN1.py &
  python3 /home/ubuntu/Desktop/dieustp/FET1.py &
  python3 /home/ubuntu/Desktop/dieustp/WOO1.py &
  python3 /home/ubuntu/Desktop/dieustp/HNT1.py &
  python3 /home/ubuntu/Desktop/dieustp/DCR1.py &
  python3 /home/ubuntu/Desktop/dieustp/XEM1.py &
  python3 /home/ubuntu/Desktop/dieustp/T1.py &
  python3 /home/ubuntu/Desktop/dieustp/TFUEL1.py &
  python3 /home/ubuntu/Desktop/dieustp/SSV1.py &
  python3 /home/ubuntu/Desktop/dieustp/BAL1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/dieustp/BAL1.py &
  python3 /home/ubuntu/Desktop/dieustp/ONE1.py &
  python3 /home/ubuntu/Desktop/dieustp/GALA1.py &
  python3 /home/ubuntu/Desktop/dieustp/JASMY1.py &
  python3 /home/ubuntu/Desktop/dieustp/SUSHI1.py &
  python3 /home/ubuntu/Desktop/dieustp/ENS1.py &
  python3 /home/ubuntu/Desktop/dieustp/USTC1.py &
  python3 /home/ubuntu/Desktop/dieustp/OCEAN1.py &
  python3 /home/ubuntu/Desktop/dieustp/KSM1.py &
  python3 /home/ubuntu/Desktop/dieustp/IOTX1.py &
  python3 /home/ubuntu/Desktop/dieustp/ANKR1.py &
  python3 /home/ubuntu/Desktop/dieustp/QTUM1.py &
  python3 /home/ubuntu/Desktop/dieustp/GMT1.py &
  python3 /home/ubuntu/Desktop/dieustp/AUDIO1.py &
  python3 /home/ubuntu/Desktop/dieustp/INJWAVES1.py &
  python3 /home/ubuntu/Desktop/dieustp/YFI1.py &
  python3 /home/ubuntu/Desktop/dieustp/MASK1.py &
  python3 /home/ubuntu/Desktop/dieustp/GLMR1.py &
  python3 /home/ubuntu/Desktop/dieustp/LPT1.py &
  python3 /home/ubuntu/Desktop/dieustp/GLM1.py &
  python3 /home/ubuntu/Desktop/dieustp/JST1.py &
  python3 /home/ubuntu/Desktop/dieustp/KDA1.py &
  python3 /home/ubuntu/Desktop/dieustp/BAND1.py &
  python3 /home/ubuntu/Desktop/dieustp/FLUX1.py &
  python3 /home/ubuntu/Desktop/dieustp/SC1.py &
  python3 /home/ubuntu/Desktop/dieustp/OMG1.py &
  python3 /home/ubuntu/Desktop/dieustp/SKL1.py &
  python3 /home/ubuntu/Desktop/dieustp/ICX1.py &
  python3 /home/ubuntu/Desktop/dieustp/ZRX1.py &
  python3 /home/ubuntu/Desktop/dieustp/HIVE1.py &
  python3 /home/ubuntu/Desktop/dieustp/AMP1.py &
  python3 /home/ubuntu/Desktop/dieustp/ONT1.py &
  python3 /home/ubuntu/Desktop/dieustp/IOST1.py &
  python3 /home/ubuntu/Desktop/dieustp/RSR1.py &
  python3 /home/ubuntu/Desktop/dieustp/SFP1.py &
  python3 /home/ubuntu/Desktop/dieustp/SXP1.py &
  python3 /home/ubuntu/Desktop/dieustp/ZEN1.py &
  python3 /home/ubuntu/Desktop/dieustp/ILV1.py &
  python3 /home/ubuntu/Desktop/dieustp/WAXP1.py &
  python3 /home/ubuntu/Desktop/dieustp/BICO1.py &
  python3 /home/ubuntu/Desktop/dieustp/RLC1.py &
  python3 /home/ubuntu/Desktop/dieustp/CFX1.py &
  python3 /home/ubuntu/Desktop/dieustp/STORJ1.py &
  python3 /home/ubuntu/Desktop/dieustp/SYS1.py &
  python3 /home/ubuntu/Desktop/dieustp/DGB1.py &
  python3 /home/ubuntu/Desktop/dieustp/CKB1.py &
  python3 /home/ubuntu/Desktop/dieustp/CELR1.py &
  python3 /home/ubuntu/Desktop/dieustp/VGX1.py &
  python3 /home/ubuntu/Desktop/dieustp/PEOPLE1.py &
  python3 /home/ubuntu/Desktop/dieustp/STG1.py &
  python3 /home/ubuntu/Desktop/dieustp/LSK1.py &
  python3 /home/ubuntu/Desktop/dieustp/UMA1.py &
  python3 /home/ubuntu/Desktop/dieustp/HOOK1.py &
  python3 /home/ubuntu/Desktop/dieustp/CHR1.py &
  python3 /home/ubuntu/Desktop/dieustp/KNC1.py &
  python3 /home/ubuntu/Desktop/dieustp/SCRT1.py &
  python3 /home/ubuntu/Desktop/dieustp/ELF1.py &
  python3 /home/ubuntu/Desktop/dieustp/HFT1.py &
  python3 /home/ubuntu/Desktop/dieustp/SLP1.py &
  python3 /home/ubuntu/Desktop/dieustp/PLA1.py &
  python3 /home/ubuntu/Desktop/dieustp/API31.py &
  python3 /home/ubuntu/Desktop/dieustp/PUNDIX1.py &
  python3 /home/ubuntu/Desktop/dieustp/MOB1.py &
  python3 /home/ubuntu/Desktop/dieustp/NMR1.py &
  python3 /home/ubuntu/Desktop/dieustp/GAL1.py &
  python3 /home/ubuntu/Desktop/dieustp/XNO1.py &
  python3 /home/ubuntu/Desktop/dieustp/MC1.py &
  python3 /home/ubuntu/Desktop/dieustp/ANT1.py &
  python3 /home/ubuntu/Desktop/dieustp/GTC1.py &
  python3 /home/ubuntu/Desktop/dieustp/SNT1.py &
  python3 /home/ubuntu/Desktop/dieustp/GFT1.py &
  python3 /home/ubuntu/Desktop/dieustp/CVC1.py &
  python3 /home/ubuntu/Desktop/dieustp/COTI1.py &
  python3 /home/ubuntu/Desktop/dieustp/POLYX1.py &
  python3 /home/ubuntu/Desktop/dieustp/CTSI1.py &
  python3 /home/ubuntu/Desktop/dieustp/PYR1.py &
  python3 /home/ubuntu/Desktop/dieustp/DUSK1.py &
  python3 /home/ubuntu/Desktop/dieustp/REQ1.py &
  python3 /home/ubuntu/Desktop/dieustp/DEXE1.py &
  python3 /home/ubuntu/Desktop/dieustp/ONG1.py &
  python3 /home/ubuntu/Desktop/dieustp/STEEM1.py &
  python3 /home/ubuntu/Desktop/dieustp/HIGH1.py &
  python3 /home/ubuntu/Desktop/dieustp/ARDR1.py &
  python3 /home/ubuntu/Desktop/dieustp/ALPHA1.py &
  python3 /home/ubuntu/Desktop/dieustp/DENT1.py &
  python3 /home/ubuntu/Desktop/dieustp/RAD1.py &
  python3 /home/ubuntu/Desktop/dieustp/PHA1.py &
  python3 /home/ubuntu/Desktop/dieustp/POWR1.py &
  python3 /home/ubuntu/Desktop/dieustp/SRM1.py &
  python3 /home/ubuntu/Desktop/dieustp/MBOX1.py &
  python3 /home/ubuntu/Desktop/dieustp/PROM1.py &
  python3 /home/ubuntu/Desktop/dieustp/SPELL1.py &
  python3 /home/ubuntu/Desktop/dieustp/IQ1.py &
  python3 /home/ubuntu/Desktop/dieustp/REN1.py &
  python3 /home/ubuntu/Desktop/dieustp/MDX1.py &
  python3 /home/ubuntu/Desktop/dieustp/WIN1.py &
  python3 /home/ubuntu/Desktop/dieustp/ACH1.py &
  python3 /home/ubuntu/Desktop/dieustp/XVS1.py &
  python3 /home/ubuntu/Desktop/dieustp/NKN1.py &
  python3 /home/ubuntu/Desktop/dieustp/STRAX1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/dieustp/STRAX1.py &
  python3 /home/ubuntu/Desktop/dieustp/XRPUP1.py &
  python3 /home/ubuntu/Desktop/dieustp/XRPDOWN1.py &
  python3 /home/ubuntu/Desktop/dieustp/MULTI1.py &
  python3 /home/ubuntu/Desktop/dieustp/LINKUP1.py &
  python3 /home/ubuntu/Desktop/dieustp/LINKDOWN1.py &
  python3 /home/ubuntu/Desktop/dieustp/HIFI1.py &
  python3 /home/ubuntu/Desktop/dieustp/GBP1.py &
  python3 /home/ubuntu/Desktop/dieustp/EUR1.py &
  python3 /home/ubuntu/Desktop/dieustp/ETHUP1.py &
  python3 /home/ubuntu/Desktop/dieustp/ETHDOWN1.py &
  python3 /home/ubuntu/Desktop/dieustp/BTCUP1.py &
  python3 /home/ubuntu/Desktop/dieustp/BTCDOWN1.py &
  python3 /home/ubuntu/Desktop/dieustp/BNBUP1.py &
  python3 /home/ubuntu/Desktop/dieustp/BNBDOWN1.py &
  python3 /home/ubuntu/Desktop/dieustp/BETH1.py &
  python3 /home/ubuntu/Desktop/dieustp/AUD1.py &
  python3 /home/ubuntu/Desktop/dieustp/ADAP1.py &
  python3 /home/ubuntu/Desktop/dieustp/ADADOWN1.py &
  python3 /home/ubuntu/Desktop/dieustp/JUV1.py &
  python3 /home/ubuntu/Desktop/dieustp/OG1.py &
  python3 /home/ubuntu/Desktop/dieustp/PERL1.py &
  python3 /home/ubuntu/Desktop/dieustp/ATM1.py &
  python3 /home/ubuntu/Desktop/dieustp/UFT1.py &
  python3 /home/ubuntu/Desktop/dieustp/CVP1.py &
  python3 /home/ubuntu/Desktop/dieustp/PNT1.py &
  python3 /home/ubuntu/Desktop/dieustp/ACM1.py &
  python3 /home/ubuntu/Desktop/dieustp/MIR1.py &
  python3 /home/ubuntu/Desktop/dieustp/TORN1.py &
  python3 /home/ubuntu/Desktop/dieustp/OAX1.py &
  python3 /home/ubuntu/Desktop/dieustp/WABI1.py &
  python3 /home/ubuntu/Desktop/dieustp/AKRO1.py &
  python3 /home/ubuntu/Desktop/dieustp/FOR1.py &
  python3 /home/ubuntu/Desktop/dieustp/PROS1.py &
  python3 /home/ubuntu/Desktop/dieustp/ANC1.py &
  python3 /home/ubuntu/Desktop/dieustp/DREP1.py &
  python3 /home/ubuntu/Desktop/dieustp/AST1.py &
  python3 /home/ubuntu/Desktop/dieustp/VIB1.py &
  python3 /home/ubuntu/Desktop/dieustp/DF1.py &
  python3 /home/ubuntu/Desktop/dieustp/WTC1.py &
  python3 /home/ubuntu/Desktop/dieustp/OOKI1.py &
  python3 /home/ubuntu/Desktop/dieustp/DOCK1.py &
  python3 /home/ubuntu/Desktop/dieustp/AION1.py &
  python3 /home/ubuntu/Desktop/dieustp/FIDA1.py &
  python3 /home/ubuntu/Desktop/dieustp/KEY1.py &
  python3 /home/ubuntu/Desktop/dieustp/FRONT1.py &
  python3 /home/ubuntu/Desktop/dieustp/EPX1.py &
  python3 /home/ubuntu/Desktop/dieustp/AMB1.py &
  python3 /home/ubuntu/Desktop/dieustp/CREAM1.py &
  python3 /home/ubuntu/Desktop/dieustp/VITE1.py &
  python3 /home/ubuntu/Desktop/dieustp/PORTO1.py &
  python3 /home/ubuntu/Desktop/dieustp/OM1.py &
  python3 /home/ubuntu/Desktop/dieustp/BURGER1.py &
  python3 /home/ubuntu/Desktop/dieustp/AUTO1.py &
  python3 /home/ubuntu/Desktop/dieustp/HARD1.py &
  python3 /home/ubuntu/Desktop/dieustp/WING1.py &
  python3 /home/ubuntu/Desktop/dieustp/FARM1.py &
  python3 /home/ubuntu/Desktop/dieustp/PSG1.py &
  python3 /home/ubuntu/Desktop/dieustp/ADX1.py &
  python3 /home/ubuntu/Desktop/dieustp/TROY1.py &
  python3 /home/ubuntu/Desktop/dieustp/COS1.py &
  python3 /home/ubuntu/Desktop/dieustp/CITY1.py &
  python3 /home/ubuntu/Desktop/dieustp/SANTOS1.py &
  python3 /home/ubuntu/Desktop/dieustp/QLS1.py &
  python3 /home/ubuntu/Desktop/dieustp/POLS1.py &
  python3 /home/ubuntu/Desktop/dieustp/ALPACA1.py &
  python3 /home/ubuntu/Desktop/dieustp/PHB1.py &
  python3 /home/ubuntu/Desktop/dieustp/SNM1.py &
  python3 /home/ubuntu/Desktop/dieustp/TRU1.py &
  python3 /home/ubuntu/Desktop/dieustp/PERP1.py &
  python3 /home/ubuntu/Desktop/dieustp/WAN1.py &
  python3 /home/ubuntu/Desktop/dieustp/LTO1.py &
  python3 /home/ubuntu/Desktop/dieustp/DEGO1.py &
  python3 /home/ubuntu/Desktop/dieustp/AUCTION1.py &
  python3 /home/ubuntu/Desktop/dieustp/BOND1.py &
  python3 /home/ubuntu/Desktop/dieustp/BIFI1.py &
  python3 /home/ubuntu/Desktop/dieustp/KMD1.py &
  python3 /home/ubuntu/Desktop/dieustp/ALPINE1.py &
  python3 /home/ubuntu/Desktop/dieustp/TOMO1.py &
  python3 /home/ubuntu/Desktop/dieustp/ALCX1.py &
  python3 /home/ubuntu/Desktop/dieustp/IDEX1.py &
  python3 /home/ubuntu/Desktop/dieustp/DIA1.py &
  python3 /home/ubuntu/Desktop/dieustp/REI1.py &
  python3 /home/ubuntu/Desktop/dieustp/LEVER1.py &
  python3 /home/ubuntu/Desktop/dieustp/FIS1.py &
  python3 /home/ubuntu/Desktop/dieustp/LINA1.py &
  python3 /home/ubuntu/Desktop/dieustp/MDT1.py &
  python3 /home/ubuntu/Desktop/dieustp/AGLD1.py &
  python3 /home/ubuntu/Desktop/dieustp/QI1.py &
  python3 /home/ubuntu/Desktop/dieustp/VIDT1.py &
  python3 /home/ubuntu/Desktop/dieustp/AVA1.py &
  python3 /home/ubuntu/Desktop/dieustp/ERN1.py &
  python3 /home/ubuntu/Desktop/dieustp/BTS1.py &
  python3 /home/ubuntu/Desktop/dieustp/KP3R1.py &
  python3 /home/ubuntu/Desktop/dieustp/CLV1.py &
  python3 /home/ubuntu/Desktop/dieustp/CHESS1.py &
  python3 /home/ubuntu/Desktop/dieustp/ORN1.py &
  python3 /home/ubuntu/Desktop/dieustp/BLZ1.py &
  python3 /home/ubuntu/Desktop/dieustp/VOXEL1.py &
  python3 /home/ubuntu/Desktop/dieustp/PIVX1.py &
  sleep 10
  python3 /home/ubuntu/Desktop/dieustp/PIVX1.py &
  python3 /home/ubuntu/Desktop/dieustp/GAS1.py &
  python3 /home/ubuntu/Desktop/dieustp/FIRO1.py &
  python3 /home/ubuntu/Desktop/dieustp/NEBL1.py &
  python3 /home/ubuntu/Desktop/dieustp/BAR1.py &
  python3 /home/ubuntu/Desktop/dieustp/DATA1.py &
  python3 /home/ubuntu/Desktop/dieustp/QUICK1.py &
  python3 /home/ubuntu/Desktop/dieustp/LAZIO1.py &
  python3 /home/ubuntu/Desktop/dieustp/BEL1.py &
  python3 /home/ubuntu/Desktop/dieustp/UNFI1.py &
  python3 /home/ubuntu/Desktop/dieustp/IRIS1.py &
  python3 /home/ubuntu/Desktop/dieustp/NULS1.py &
  python3 /home/ubuntu/Desktop/dieustp/TRB1.py &
  python3 /home/ubuntu/Desktop/dieustp/FIO1.py &
  python3 /home/ubuntu/Desktop/dieustp/POND1.py &
  python3 /home/ubuntu/Desktop/dieustp/JOE1.py &
  python3 /home/ubuntu/Desktop/dieustp/VTHO1.py &
  python3 /home/ubuntu/Desktop/dieustp/ACA1.py &
  python3 /home/ubuntu/Desktop/dieustp/BSW1.py &
  python3 /home/ubuntu/Desktop/dieustp/FUN1.py &
  python3 /home/ubuntu/Desktop/dieustp/ALICE1.py &
  python3 /home/ubuntu/Desktop/dieustp/TLM1.py &
  python3 /home/ubuntu/Desktop/dieustp/CTK1.py &
  python3 /home/ubuntu/Desktop/dieustp/WRX1.py &
  python3 /home/ubuntu/Desktop/dieustp/OGN1.py &
  python3 /home/ubuntu/Desktop/dieustp/REEF1.py &
  python3 /home/ubuntu/Desktop/dieustp/BNT1.py &
  python3 /home/ubuntu/Desktop/dieustp/DAR1.py &
  python3 /home/ubuntu/Desktop/dieustp/QKC1.py &
  python3 /home/ubuntu/Desktop/dieustp/MTL1.py &
  python3 /home/ubuntu/Desktop/dieustp/OXT1.py &
  python3 /home/ubuntu/Desktop/dieustp/STMX1.py &
  python3 /home/ubuntu/Desktop/dieustp/DODO1.py &
  python3 /home/ubuntu/Desktop/dieustp/BETA1.py &
  python3 /home/ubuntu/Desktop/dieustp/ATA1.py &
  python3 /home/ubuntu/Desktop/dieustp/C981.py &
  python3 /home/ubuntu/Desktop/dieustp/ARK1.py &
  python3 /home/ubuntu/Desktop/dieustp/FORTH1.py &
  python3 /home/ubuntu/Desktop/dieustp/RIF1.py &
  python3 /home/ubuntu/Desktop/dieustp/YGG1.py &
  python3 /home/ubuntu/Desktop/dieustp/LOOM1.py &
  python3 /home/ubuntu/Desktop/dieustp/UTK1.py &
  python3 /home/ubuntu/Desktop/dieustp/AERGO1.py &
  python3 /home/ubuntu/Desktop/dieustp/MBL1.py &
  python3 /home/ubuntu/Desktop/dieustp/SUN1.py &
  python3 /home/ubuntu/Desktop/dieustp/BADGER1.py &
  python3 /home/ubuntu/Desktop/dieustp/SUPER1.py &
  python3 /home/ubuntu/Desktop/dieustp/MOVR1.py &
  python3 /home/ubuntu/Desktop/dieustp/CTXC1.py &
  python3 /home/ubuntu/Desktop/dieustp/RARE1.py &
  python3 /home/ubuntu/Desktop/dieustp/TKO1.py &
  python3 /home/ubuntu/Desktop/dieustp/RAY1.py &
  python3 /home/ubuntu/Desktop/dieustp/XVG1.py &
  python3 /home/ubuntu/Desktop/dieustp/LIT1.py &
  python3 /home/ubuntu/Desktop/dieustp/COCOS1.py &
  python3 /home/ubuntu/Desktop/dieustp/WNXM1.py &
  python3 /home/ubuntu/Desktop/dieustp/ARPA1.py &
  python3 /home/ubuntu/Desktop/dieustp/GHST1.py &
  python3 /home/ubuntu/Desktop/dieustp/MLN1.py &
  python3 /home/ubuntu/Desktop/dieustp/BAKE1.py &
  python3 /home/ubuntu/Desktop/dieustp/YFII1.py &
  python3 /home/ubuntu/Desktop/dieustp/TVK1.py &
  python3 /home/ubuntu/Desktop/dieustp/FLM1.py &
  python3 /home/ubuntu/Desktop/dieustp/LOKA1.py 

clear
done
